export const HOME_BLOCK_TYPES = {
  ITEM: 'ITEM',
  USER: 'USER',
  BRAND: 'BRAND',
  CATEGORY: 'CATEGORY'
};

export const HOME_BLOCK_SEE_MORE_POSITION = {
  HEADER: 'HEADER',
  CONTENT: 'CONTENT',
  BOTTOM: 'BOTTOM'
};

export const HOME_BLOCK_PROPERTY_TYPES = {
  STRING: 'STRING',
  NUMBER: 'NUMBER',
  BOOLEAN: 'BOOLEAN',
  ENUM: 'ENUM',
  COLOR: 'COLOR'
};

export const HOME_BLOCK_UI_TYPES = {
  SWIPER: 'SWIPER',
  GRID: 'GRID'
};

export const HOME_BLOCK_USER_STATE_AUTH = {
  CONNECTED: 'CONNECTED',
  NOT_CONNECTED: 'NOT_CONNECTED',
  BOTH: 'BOTH'
};

export const HOME_BLOCK_TITLE_SIZES = {
  SM: 'SM',
  MD: 'MD',
  LG: 'LG',
  XL: 'XL'
};

export const HOME_BLOCK_QUERIES = {
  RECOMMENDED_ITEMS: 'RECOMMENDED_ITEMS',
  RECOMMENDED_USERS: 'RECOMMENDED_USERS',
  RECOMMENDED_BRANDS: 'RECOMMENDED_BRANDS',
  RECOMMENDED_CATEGORIES: 'RECOMMENDED_CATEGORIES',
  LAST_ITEMS: 'LAST_ITEMS',
  SIMILAR_ITEMS: 'LAST_ITEMS',
  FAVORITES_ITEMS: 'FAVORITES_ITEMS',
  POPULAR_BRANDS: 'POPULAR_BRANDS',
  POPULAR_CATEGORIES: 'POPULAR_CATEGORIES',
  POPULAR_USERS: 'POPULAR_USERS',
  RECOMMENDED_AND_POPULAR_BRANDS: 'RECOMMENDED_AND_POPULAR_BRANDS',
  RECOMMENDED_AND_POPULAR_CATEGORIES: 'RECOMMENDED_AND_POPULAR_CATEGORIES',
  RECOMMENDED_AND_POPULAR_USERS: 'RECOMMENDED_AND_POPULAR_USERS'
};

export const HOME_BLOCK_QUERIES_BY_TYPE = {
  [HOME_BLOCK_TYPES.ITEM]: [
    HOME_BLOCK_QUERIES.LAST_ITEMS,
    HOME_BLOCK_QUERIES.RECOMMENDED_ITEMS,
    HOME_BLOCK_QUERIES.FAVORITES_ITEMS
  ],
  [HOME_BLOCK_TYPES.USER]: [
    HOME_BLOCK_QUERIES.RECOMMENDED_USERS,
    HOME_BLOCK_QUERIES.RECOMMENDED_POPULAR_USERS,
    HOME_BLOCK_QUERIES.POPULAR_USERS
  ],
  [HOME_BLOCK_TYPES.BRAND]: [
    HOME_BLOCK_QUERIES.RECOMMENDED_BRANDS,
    HOME_BLOCK_QUERIES.RECOMMENDED_POPULAR_BRANDS,
    HOME_BLOCK_QUERIES.POPULAR_BRANDS
  ],
  [HOME_BLOCK_TYPES.CATEGORY]: [
    HOME_BLOCK_QUERIES.RECOMMENDED_CATEGORIES,
    HOME_BLOCK_QUERIES.RECOMMENDED_POPULAR_CATEGORIES,
    HOME_BLOCK_QUERIES.POPULAR_CATEGORIES
  ]
};

export const HOME_BLOCK_QUERIES_ONLY_CONNECTED = [
  HOME_BLOCK_QUERIES.FAVORITES_ITEMS
];
