export const HOME_BLOCK_TYPES = {
  ITEM: 'ITEM',
  USER: 'USER',
  BRAND: 'BRAND',
  CATEGORY: 'CATEGORY'
};

export const HOME_BLOCK_SEE_MORE_POSITION = {
  HEADER: 'HEADER',
  CONTENT: 'CONTENT',
  BOTTOM: 'BOTTOM'
};

export const HOME_BLOCK_PROPERTY_TYPES = {
  STRING: 'STRING',
  NUMBER: 'NUMBER',
  BOOLEAN: 'BOOLEAN',
  ENUM: 'ENUM',
  COLOR: 'COLOR'
};

export const HOME_BLOCK_UI_TYPES = {
  SWIPER: 'SWIPER',
  GRID: 'GRID'
};

export const HOME_BLOCK_QUERIES = {
  [HOME_BLOCK_TYPES.ITEM]: {
    LAST: 'LAST_ITEMS',
    RECOMMENDED: 'RECOMMENDED_ITEMS'
  },
  [HOME_BLOCK_TYPES.USER]: {
    RECOMMENDED: 'RECOMMENDED_USERS',
    RECOMMENDED_POPULAR: 'RECOMMENDED_POPULAR_USERS',
    POPULAR: 'POPULAR_USERS'
  },
  [HOME_BLOCK_TYPES.BRAND]: {
    RECOMMENDED: 'RECOMMENDED_BRANDS',
    RECOMMENDED_POPULAR: 'RECOMMENDED_POPULAR_BRANDS',
    POPULAR: 'POPULAR_BRANDS'
  },
  [HOME_BLOCK_TYPES.CATEGORY]: {
    RECOMMENDED: 'RECOMMENDED_CATEGORIES',
    RECOMMENDED_POPULAR: 'RECOMMENDED_POPULAR_CATEGORIES',
    POPULAR: 'POPULAR_CATEGORIES'
  }
};
