export const ITEM_PUBLICATION_STATE_TRANSITIONS = {
  DELETE_PUBLISHED_ITEM: 'DELETE_PUBLISHED_ITEM',
  DELETE_VACANCY_MODE_ITEM: 'DELETE_VACANCY_MODE_ITEM',
  SET_VACANCY_MODE: 'SET_VACANCY_MODE',
  REMOVE_VACANCY_MODE: 'REMOVE_VACANCY_MODE',
  ORDER: 'ORDER',
  PURCHASE: 'PURCHASE',
  UNPUBLISHED_ORDERED_ITEM: 'UNPUBLISHED_ORDERED_ITEM',
  UNPUBLISH: 'UNPUBLISH',
  REPUBLISH: 'REPUBLISH',
  DELETE_UNPUBLISHED_ITEM: 'DELETE_UNPUBLISHED_ITEM'
};

export const ITEM_PUBLICATION_STATES = {
  PUBLISHED: 'PUBLISHED',
  VACANCY: 'VACANCY',
  ORDERED: 'ORDERED',
  PURCHASED: 'PURCHASED',
  UNPUBLISHED: 'UNPUBLISHED',
  DELETED: 'DELETED'
};
